version: '3'

services:

  node:
    image: node:16.14.2-buster
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  python:
    build:
      context: ./side_m
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    tty: true
